In [1]:
import pandas as pd

In [3]:
dados = pd.read_csv('Anime_rank.csv')
dados

,UID,Title,Rank,Stream type,Episodes,Start date,End date,Members,Score
0,1,Sousou no Frieren,1,TV,28.0,Sep 2023,Mar 2024,"800,615",9.35
1,2,Fullmetal Alchemist: Brotherhood,2,TV,64.0,Apr 2009,Jul 2010,"3,373,923",9.09
2,3,Steins;Gate,3,TV,24.0,Apr 2011,Sep 2011,"2,584,616",9.07
3,4,Gintama°,4,TV,51.0,Apr 2015,Mar 2016,"636,631",9.06
4,5,Shingeki no Kyojin Season 3 Part 2,5,TV,10.0,Apr 2019,Jul 2019,"2,305,044",9.05
...,...,...,...,...,...,...,...,...,...
8645,8646,Hypersonic Music Club,8646,ONA,1.0,Aug 2023,Aug 2023,383,6.15
8646,8647,Iron Man: Rise of Technovore,8647,OVA,1.0,Apr 2013,Apr 2013,"8,616",6.15
8647,8648,Jewelpet Movie: Sweets Dance Princess,8648,Movie,1.0,Aug 2012,Aug 2012,"1,797",6.15
8648,8649,Si Hai Jing Qi,8649,ONA,12.0,Aug 2018,Nov 2018,911,6.15
8649,8650,Sore Ike! Anpanman: Black Nose to Mahou no Uta,8650,Movie,1.0,Jul 2010,Jul 2010,620,6.15

In [ ]:
dados = dados[['Title', 'Score']]
dados

In [7]:
dados.to_csv('Dados.csv', index=False)

In [11]:
dados.to_excel('Dados.xlsx', index=False)